datasource:
  epg:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ai_epg?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: cms
    password: cms@ai
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    max-wait-millis: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 30000
    max-active: 20
    max-idle: 5
    min-idle: 2
    initial-size: 3
  cms:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ai_cms?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: cms
    password: cms@ai
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    max-wait-millis: 30000
    validation-query: select 1
    time-between-eviction-runs-millis: 30000
    max-active: 20
    max-idle: 5
    min-idle: 1
    initial-size: 1

            
image:
  upload:
    path: /usr/local/nginx/html/image
  web:
    path: http://172.25.137.2/image
  ftp:
    path: ftp://cms:cms1234qwer@172.25.137.2:21/image
      
xml:
  upload:
    path: /usr/local/nginx/html/xml
  web:
    path: http://172.25.137.2/xml
  ftp:
    path: ftp://cms:cms1234qwer@172.25.137.2:21/xml
    
video:
  upload:
    path: /usr/local/nginx/html/video
  web:
    path: http://172.25.137.2/video
  ftp:
    path: ftp://cms:cms1234qwer@172.25.137.2:21/video

  
injection:
  task.schedule: 0 0/1 * * * ?
  task.maxNum: 20
  task.maxRequestTimes: 3

download:
  enabled: true
  task.schedule: 0 0/1 * * * ?
  task.maxNum: 3
  task.maxRequestTimes: 3
  task.timeout: 12